host_a:
  build: nginx-custom
  ports:
    - "10080:80"
  volumes:
    - ~/yanosuke/dit-training-FY34/dit-training-FY34/t02/fuku-y/public_html:/usr/share/nginx/html:ro 
  command:
    nginx -g 'daemon off;'
